language: rust

rust:
  - stable
  - beta
  - nightly

  # The min version here should match junipers min required version
  # https://github.com/graphql-rust/juniper/blob/master/juniper/CHANGELOG.md
  # Current stable version: 1.34.0
  - 1.33.0
  - 1.32.0
  - 1.31.0
  - 1.30.0

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --check
  - cargo test --all
  - bin/run_all_examples
