name: Assign author to PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Assign Author
      uses: technote-space/assign-author@v1.2.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
